DROP TABLE IF EXISTS Poll1;

CREATE TABLE IF NOT EXISTS Poll1 (
    Id INTEGER PRIMARY KEY,
    Key TEXT NOT NULL,
    Value TEXT,
    IP TEXT,
    Time TEXT
);

CREATE INDEX IF NOT EXISTS idx_poll1_key ON Poll1(Key)